### ISSUE TITLE
🐛 Problem with end-to-end tests

### ISSUE THREAD

**Issue by Rolitoansu** [Arquisoft/wichat_en1b#235]
We are encountering a problem when we try to execute the end-to-end tests. They throw an error because the "socket hang up":

<img width="501" alt="Image" src="https://github.com/user-attachments/assets/f0a4baa3-6eb7-4730-bc29-18cecc9c807b" />

@saulmf also tried to run the tests and he was given a different error:

![Image](https://github.com/user-attachments/assets/6b985009-cf1a-45df-9589-58bf2d893924)

@uo288583 is able to run the tests if he brings down the front-end and runs them, but if I try that, I am given an error because the back-end ports are already in use:

<img width="1001" alt="Image" src="https://github.com/user-attachments/assets/b2d6df4f-a92c-418d-8c0c-263822be8b02" />

We don't know the reason behind this. What could be the problem? @pglez82

**Comment by pglez82** [comment]
If you use the method that I explained in class, everything should be down before running the e2e tests because the script test-environment-setup.js is in charge of launching everything. So ports should be available to start everything before launching the tests.

If you cannot get it, on monday I can try to execute them given than you provide me with enough information (what branch has the code that is giving problems, what command are you executing for running the tests, etc.)

**Comment by Rolitoansu** [comment]
The branch in which we're testing them is: [e2e_implementation](https://github.com/Arquisoft/wichat_en1b/tree/e2e_implementation). I try to run the tests by means of the command `npm --prefix webapp run test:e2e`. I usually install the dependencies and build it previously.

We can take a look tomorrow, and if everything seems to work we just merge the branch into master.

Thank you very much!

**Comment by uo288583** [comment]
The issue was reviewed and solved in Minutes Session 11

**Comment by saulmf** [comment]
I reopened the issue because @Rolitoansu and I (@saulmf ) are still unable to run the tests. Raúl is still getting the error "socket hang up" and I don't know if I'm doing something wrong, but when I execute the command "npm --prefix webapp run test:e2e" or "npm run --prefix webapp test:e2e", (after installing all dependencies of all modules with "npm install" and testing that the services run correctly with docker) I get a 404 not found error: 

![Image](https://github.com/user-attachments/assets/fbcb9a8e-1c51-4aae-9ed3-b908cfd91cdc)

**Comment by saulmf** [comment]
I would appreciate if someone is able to correctly run the e2e tests to document here the steps they took (and perhaps adding some screenshot).

**Comment by uo288583** [comment]
The issue continues to happen to the others members of the group and for me seem to continue working

![Image](https://github.com/user-attachments/assets/575cdf40-81d5-48c6-b633-74e5c54962b4)

![Image](https://github.com/user-attachments/assets/186d06bc-8892-47fd-b4c9-98ad3421ed40)

**Comment by saulmf** [comment]
I have found that if I have all the containers running in docker when I execute the tests, I get a warning regarding the occupied ports but the e2e tests run:

![Image](https://github.com/user-attachments/assets/3112f8bb-cc71-4570-864f-202e32673cb5)

![Image](https://github.com/user-attachments/assets/75b381cb-2cc2-4b15-abae-6eaf434bcdab)

**Comment by Br1NKOL** [comment]
It working for me, steps I did:
- Go to all services and npm install manually.
- In the package.json of webapp remove CI=false in the **build** script.
- Run in ./webapp
     - npm run build
     - npm run test:e2e

![Image](https://github.com/user-attachments/assets/5ba1ca2e-984a-4465-819b-3744935ea5fe)

**Comment by saulmf** [comment]
Okey, so as was explained in the pull request (https://github.com/Arquisoft/wichat_en1b/pull/245), the project README file should be updated with a new section explaining how to run the e2e tests. It should also explain that we need a new .env file with the JWT_SECRET in the webapp folder in order to run the e2e tests.

We still need to investigate on the consequences of removing the "CI=false" in the build script of the webapp package.json.

**Comment by uo288583** [comment]
By adding the cross-env property in the build script it now works for me @uo288583 and for @saulmf, this dependency makes the "CI=false" (which prevents the build to stop when encountering minor issues) work evenly in every OS and thus correcting the previous build error.

![Image](https://github.com/user-attachments/assets/18a1d978-f633-436e-be5e-3c08ec8f986b)
